name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python deps
        run: pip install -r services/appointment_service/requirements.txt
      - name: Run unit tests
        run: pytest services/appointment_service/app/test_main.py

  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/aws
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - run: terraform fmt -check
      - run: terraform init -backend=false
      - run: terraform validate
